// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v7.34.0
// source: bridge.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "ephemera.pubsub";

export interface PublishRequest {
  data: string;
}

export interface PublishResponse {
  ok: boolean;
  error: string;
}

export interface StreamMessagesRequest {
}

export interface Message {
  data: string;
}

export interface GetRemoteServersRequest {
}

export interface GetRemoteServersResponse {
  hosts: string[];
}

function createBasePublishRequest(): PublishRequest {
  return { data: "" };
}

export const PublishRequest: MessageFns<PublishRequest> = {
  encode(message: PublishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishRequest {
    return { data: isSet(object.data) ? globalThis.String(object.data) : "" };
  },

  toJSON(message: PublishRequest): unknown {
    const obj: any = {};
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PublishRequest>, I>>(base?: I): PublishRequest {
    return PublishRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishRequest>, I>>(object: I): PublishRequest {
    const message = createBasePublishRequest();
    message.data = object.data ?? "";
    return message;
  },
};

function createBasePublishResponse(): PublishResponse {
  return { ok: false, error: "" };
}

export const PublishResponse: MessageFns<PublishResponse> = {
  encode(message: PublishResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: PublishResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PublishResponse>, I>>(base?: I): PublishResponse {
    return PublishResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishResponse>, I>>(object: I): PublishResponse {
    const message = createBasePublishResponse();
    message.ok = object.ok ?? false;
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseStreamMessagesRequest(): StreamMessagesRequest {
  return {};
}

export const StreamMessagesRequest: MessageFns<StreamMessagesRequest> = {
  encode(_: StreamMessagesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamMessagesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamMessagesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): StreamMessagesRequest {
    return {};
  },

  toJSON(_: StreamMessagesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamMessagesRequest>, I>>(base?: I): StreamMessagesRequest {
    return StreamMessagesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamMessagesRequest>, I>>(_: I): StreamMessagesRequest {
    const message = createBaseStreamMessagesRequest();
    return message;
  },
};

function createBaseMessage(): Message {
  return { data: "" };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return { data: isSet(object.data) ? globalThis.String(object.data) : "" };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.data !== "") {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.data = object.data ?? "";
    return message;
  },
};

function createBaseGetRemoteServersRequest(): GetRemoteServersRequest {
  return {};
}

export const GetRemoteServersRequest: MessageFns<GetRemoteServersRequest> = {
  encode(_: GetRemoteServersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRemoteServersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRemoteServersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetRemoteServersRequest {
    return {};
  },

  toJSON(_: GetRemoteServersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRemoteServersRequest>, I>>(base?: I): GetRemoteServersRequest {
    return GetRemoteServersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRemoteServersRequest>, I>>(_: I): GetRemoteServersRequest {
    const message = createBaseGetRemoteServersRequest();
    return message;
  },
};

function createBaseGetRemoteServersResponse(): GetRemoteServersResponse {
  return { hosts: [] };
}

export const GetRemoteServersResponse: MessageFns<GetRemoteServersResponse> = {
  encode(message: GetRemoteServersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.hosts) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRemoteServersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRemoteServersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hosts.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRemoteServersResponse {
    return { hosts: globalThis.Array.isArray(object?.hosts) ? object.hosts.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: GetRemoteServersResponse): unknown {
    const obj: any = {};
    if (message.hosts?.length) {
      obj.hosts = message.hosts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRemoteServersResponse>, I>>(base?: I): GetRemoteServersResponse {
    return GetRemoteServersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRemoteServersResponse>, I>>(object: I): GetRemoteServersResponse {
    const message = createBaseGetRemoteServersResponse();
    message.hosts = object.hosts?.map((e) => e) || [];
    return message;
  },
};

export type PubSubServiceService = typeof PubSubServiceService;
export const PubSubServiceService = {
  publish: {
    path: "/ephemera.pubsub.PubSubService/Publish",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PublishRequest): Buffer => Buffer.from(PublishRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PublishRequest => PublishRequest.decode(value),
    responseSerialize: (value: PublishResponse): Buffer => Buffer.from(PublishResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PublishResponse => PublishResponse.decode(value),
  },
  streamMessages: {
    path: "/ephemera.pubsub.PubSubService/StreamMessages",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: StreamMessagesRequest): Buffer =>
      Buffer.from(StreamMessagesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StreamMessagesRequest => StreamMessagesRequest.decode(value),
    responseSerialize: (value: Message): Buffer => Buffer.from(Message.encode(value).finish()),
    responseDeserialize: (value: Buffer): Message => Message.decode(value),
  },
  getRemoteServers: {
    path: "/ephemera.pubsub.PubSubService/GetRemoteServers",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetRemoteServersRequest): Buffer =>
      Buffer.from(GetRemoteServersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetRemoteServersRequest => GetRemoteServersRequest.decode(value),
    responseSerialize: (value: GetRemoteServersResponse): Buffer =>
      Buffer.from(GetRemoteServersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetRemoteServersResponse => GetRemoteServersResponse.decode(value),
  },
} as const;

export interface PubSubServiceServer extends UntypedServiceImplementation {
  publish: handleUnaryCall<PublishRequest, PublishResponse>;
  streamMessages: handleServerStreamingCall<StreamMessagesRequest, Message>;
  getRemoteServers: handleUnaryCall<GetRemoteServersRequest, GetRemoteServersResponse>;
}

export interface PubSubServiceClient extends Client {
  publish(
    request: PublishRequest,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  publish(
    request: PublishRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  publish(
    request: PublishRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  streamMessages(request: StreamMessagesRequest, options?: Partial<CallOptions>): ClientReadableStream<Message>;
  streamMessages(
    request: StreamMessagesRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<Message>;
  getRemoteServers(
    request: GetRemoteServersRequest,
    callback: (error: ServiceError | null, response: GetRemoteServersResponse) => void,
  ): ClientUnaryCall;
  getRemoteServers(
    request: GetRemoteServersRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetRemoteServersResponse) => void,
  ): ClientUnaryCall;
  getRemoteServers(
    request: GetRemoteServersRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetRemoteServersResponse) => void,
  ): ClientUnaryCall;
}

export const PubSubServiceClient = makeGenericClientConstructor(
  PubSubServiceService,
  "ephemera.pubsub.PubSubService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PubSubServiceClient;
  service: typeof PubSubServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
