// Generated by ts-to-zod
import { z } from "zod";

export const apiRequestSchema = z.object({});

export const apiResponseSchema = z.object({
    error: z.string().optional()
});

export const versionSchema = z.literal(0);

export const authorSchema = z.string();

export const timestampSchema = z.number();

export const hostSchema = z.string();

export const hashSchema = z.string();

export const contentTypeSchema = z.string();

export const dimensionSchema = z.object({
    width: z.number(),
    height: z.number()
});

export const signalHeaderSchema = z.tuple([hostSchema, authorSchema, timestampSchema, z.string()]);

export const signalBodySchema = z.unknown();

export const signalFooterSchema = z.unknown();

export const signalPayloadSchema = z.tuple([versionSchema, signalHeaderSchema, signalBodySchema, signalFooterSchema]);

export const signalSchema = z.tuple([signalPayloadSchema, z.string()]);

export const createPostSignalHeaderSchema = z.tuple([hostSchema, authorSchema, timestampSchema, z.literal("create_post")]);

export const createPostSignalBodySchema = z.string();

export const createPostSignalFooterSchema = z.tuple([]);

export const createPostSignalPayloadSchema = z.tuple([versionSchema, createPostSignalHeaderSchema, createPostSignalBodySchema, createPostSignalFooterSchema]);

export const postSignalSchema = z.tuple([createPostSignalPayloadSchema, z.string()]);

export const postRequestSchema = apiRequestSchema.extend({
    post: postSignalSchema
});

export const postResponseSchema = apiResponseSchema;

export const getPostsRequestSchema = apiRequestSchema.extend({
    cursor: z.string().nullable(),
    limit: z.number().optional()
});

export const getPostsResponseSchema = apiResponseSchema.extend({
    posts: z.array(postSignalSchema),
    nextCursor: z.string().nullable()
});
