// Generated by ts-to-zod
import { z } from "zod";

export const versionSchema = z.literal(0);

export const authorSchema = z.string();

export const timestampSchema = z.number();

export const hostSchema = z.string();

export const hashSchema = z.string();

export const contentTypeSchema = z.string();

export const signalHeaderSchema = z.tuple([hostSchema, authorSchema, timestampSchema, z.string()]);

export const signalBodySchema = z.unknown();

export const signalFooterSchema = z.unknown();

export const signalPayloadSchema = z.tuple([versionSchema, signalHeaderSchema, signalBodySchema, signalFooterSchema]);

export const signalSchema = z.tuple([signalPayloadSchema, z.string()]);

export const attachmentSchema = z.tuple([z.literal("attachment"), contentTypeSchema, hashSchema]);

export const createPostSignalHeaderSchema = z.tuple([hostSchema, authorSchema, timestampSchema, z.literal("create_post")]);

export const createPostSignalBodySchema = z.string();

export const createPostSignalFooterSchema = z.array(attachmentSchema);

export const createPostSignalPayloadSchema = z.tuple([versionSchema, createPostSignalHeaderSchema, createPostSignalBodySchema, createPostSignalFooterSchema]);

export const createPostSignalSchema = z.tuple([createPostSignalPayloadSchema, z.string()]);

export const deletePostSignalHeaderSchema = z.tuple([hostSchema, authorSchema, timestampSchema, z.literal("delete_post")]);

export const deletePostSignalBodySchema = z.tuple([hashSchema]);

export const deletePostSignalFooterSchema = z.tuple([]);

export const deletePostSignalPayloadSchema = z.tuple([versionSchema, deletePostSignalHeaderSchema, deletePostSignalBodySchema, deletePostSignalFooterSchema]);

export const deletePostSignalSchema = z.tuple([deletePostSignalPayloadSchema, z.string()]);

export const exportedKeyPairSchema = z.object({
    publicKey: z.string(),
    privateKey: z.string()
});

export const apiRequestSchema = z.object({});

export const apiResponseSchema = z.object({
    error: z.string().optional()
});

export const postRequestSchema = apiRequestSchema.extend({
    post: createPostSignalSchema
});

export const postResponseSchema = apiResponseSchema;

export const getPostsRequestSchema = apiRequestSchema.extend({
    cursor: z.string().optional(),
    limit: z.string().optional(),
    author: z.string().optional()
});

export const getPostsResponseSchema = apiResponseSchema.extend({
    posts: z.array(createPostSignalSchema),
    nextCursor: z.string().nullable()
});

export const deletePostRequestSchema = apiRequestSchema.extend({
    post: deletePostSignalSchema
});

export const deletePostResponseSchema = apiResponseSchema;
